### ISSUE TITLE
Could not find a package configuration file provided by "cv_bridge"

### ISSUE THREAD

**Issue by timjrobinson** [aniskoubaa/ros_essentials_cpp#1]
I'm just on Section 3, Lecture 9 of the tutorial, following all the steps. Doing a git clone of this repo and then running `catkin_make` fails with the following:

```
-- ==> add_subdirectory(ros_essentials_cpp)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Warning at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "cv_bridge" with
  any of the following names:

    cv_bridgeConfig.cmake
    cv_bridge-config.cmake

  Add the installation prefix of "cv_bridge" to CMAKE_PREFIX_PATH or set
  "cv_bridge_DIR" to a directory containing one of the above files.  If
  "cv_bridge" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  ros_essentials_cpp/CMakeLists.txt:5 (find_package)


-- Could not find the required component 'cv_bridge'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "cv_bridge" with
  any of the following names:

    cv_bridgeConfig.cmake
    cv_bridge-config.cmake

  Add the installation prefix of "cv_bridge" to CMAKE_PREFIX_PATH or set
  "cv_bridge_DIR" to a directory containing one of the above files.  If
  "cv_bridge" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  ros_essentials_cpp/CMakeLists.txt:5 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/tim/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/tim/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
```

I did a git blame on the CMakeLists file and checked out commit `1259abca16a48b0be8fea7a0338bb00a5d2e7296` which was the one just before `cv_bridge` was added and that SHA compiled fine with `catkin_make`

Is there some command I should run or dependency I should install to make cv_bridge work correctly?

**Comment by timjrobinson** [comment]
Also I'm using ros `melodic` with Debian 9.5 (stretch). 

I just ran the following:
```
sudo apt-get install ros-$(rosversion -d)-cv-bridge
sudo apt-get install ros-$(rosversion -d)-vision-opencv
sudo apt-get install ros-$(rosversion -d)-image-common
```

And now catkin_make builds correctly with the latest master.

**Comment by timjrobinson** [comment]
You might want to add that those additional packages are required to the README so others don't run into this same issue.

**Comment by juliangaal** [comment]
isn't cv-bridge already included in vision-opencv

**Comment by Souroosh96** [comment]
Hello,
I installed ROS noetic on my raspberry pi,then I created a Catkin workplace and after that I cloned a repository from github. git clone -b ros-noetic https://github.com/aniskoubaa/ros_essentials_cpp.git then I ran the two following commands as below:
Do you know how I can solve the problem?

Thanks
![1](https://user-images.githubusercontent.com/65510554/139601855-c8b7245b-49c7-4942-b5d7-eb8df89a5b6c.jpg)
![2](https://user-images.githubusercontent.com/65510554/139601858-aa8b0bcc-bd59-4a4f-8f42-19786079764f.jpg)
