### ISSUE TITLE
Error while running catkin_make

### ISSUE THREAD

**Issue by arjunsengupta1998** [aniskoubaa/ros_essentials_cpp#4]
I have been following the tutorial and had implemented several codes successfully (had tried last around a month back).
Now that I am trying to run catkin_make again, it throws an error.
(Not that I cloned the repository again and ran it as it is without making any other changes. The error persists). It would be great if you could tell me how to fix this. The error is as follows: 

CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "image_transport"
  with any of the following names:

    image_transportConfig.cmake
    image_transport-config.cmake

  Add the installation prefix of "image_transport" to CMAKE_PREFIX_PATH or
  set "image_transport_DIR" to a directory containing one of the above files.
  If "image_transport" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  ros_essentials_cpp/CMakeLists.txt:5 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/adm-user/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/adm-user/catkin_ws/build/CMakeFiles/CMakeError.log".
Makefile:1202: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

**Comment by Souroosh96** [comment]
> 
> 
> I have been following the tutorial and had implemented several codes successfully (had tried last around a month back). Now that I am trying to run catkin_make again, it throws an error. (Not that I cloned the repository again and ran it as it is without making any other changes. The error persists). It would be great if you could tell me how to fix this. The error is as follows:
> 
> CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package): Could not find a package configuration file provided by "image_transport" with any of the following names:
> 
> ```
> image_transportConfig.cmake
> image_transport-config.cmake
> ```
> 
> Add the installation prefix of "image_transport" to CMAKE_PREFIX_PATH or set "image_transport_DIR" to a directory containing one of the above files. If "image_transport" provides a separate development package or SDK, be sure it has been installed. Call Stack (most recent call first): ros_essentials_cpp/CMakeLists.txt:5 (find_package)
> 
> -- Configuring incomplete, errors occurred! See also "/home/adm-user/catkin_ws/build/CMakeFiles/CMakeOutput.log". See also "/home/adm-user/catkin_ws/build/CMakeFiles/CMakeError.log". Makefile:1202: recipe for target 'cmake_check_build_system' failed make: *** [cmake_check_build_system] Error 1 Invoking "make cmake_check_build_system" failed

Hello,How did you solve the problem?I faced the same issue.
Thank you
