### ISSUE TITLE
The turtle is not moving

### ISSUE THREAD

**Issue by siddarth09** [aniskoubaa/ros_essentials_cpp#8]
i have added the same code as shown in udemy course, but when i run the code, the turtle does not move. What can i do

**Comment by Glenn-Mendonca** [comment]
Can u show ur code or elaborate on the issue.
Issues might be:
1)Import turtle module using import turtle as *name*
2)Initialize turtle to any variable such as *variable_name* = *name*.Turtle()  
Then it should work move variable turtle, example: *variable_name*.forward(distance) #distance a number
check my code:
'''
import turtle as me  #me is just any name
t1 = me.Turtle()  #initialize t1 variable as turtle
t1.forward(100)  #move turtle
'''

**Comment by siddarth09** [comment]
I have rectfied this issue, My x,y,yaw values were not initialized and one more reason that i was not in active terminal
